### ISSUE TITLE
Syntra Development Roadmap

### ISSUE THREAD

**Issue by Ben-Rey** [massalabs/syntra#73]
# Syntra Development Roadmap

## Tasks
- [x] Deploy frontend on a hosting solution (e.g., Netlify) (1 day)
### MVP
- [x] Add MAS coin support (2 days)
- [x] #78
- [x] Improve schedule display when no schedule found (1 day)
- [x] Get failed payement and ReRun failed payement (2 day)
- [x] #80
- [x] #76
### Feedback
- [x] Internal testing and feedback (1 week)
  - [x] Ask internal coworkers to test and provide feedback
  - [x] Implement feedback from internal testing
- [x] Foundation testing and feedback (1week)
  - [x] Ask foundation to test and provide feedback
  - [x] Implement feedback from foundation
- [x] Community testing and feedback (1week)
  - [x] Ask community to test and provide feedback
  - [x] Implement feedback from community
 ### Release
- [x] Release V1 on mainnet
